# Setup
title:               Sharknia Blog
tagline:             '-'
description:         ''
url:                 https://Sharknia.github.io
baseurl:             ''
paginate:            10
permalink:           pretty

# About/contact
author:
  name:              Sharknia
  url:               https://github.com/sharknia
  email:             zel@kakao.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
