name: Deploy

on: # 어떤 작업이 수행될 때 deploy.yml 작업이 수행된다. (트리거)
  push: # push 작업이 수행될 때
    branches: # 특정 브랜치를 대상으로
      - master

permissions: # github action이 수행되는 환경에서 특정 권한을 준다
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.3.1

      - name: Install node packages
        run: yarn
        
      - name: Check lint
        run: yarn check:lint
        
      # 아래와 같은 오류가 남
      # error Command failed with exit code 1.
      # info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
      # - name: Check prettier
      #   run: yarn check:prettier
      
      - name: Build
        run: yarn build

      # - name: Install gh-pages CLI
      #   run: npm install gh-pages --save-dev

      - name: Set up GitHub token
        env:
          GITHUB_TOKEN: ${{ secrets.classicToken }}
        run: git config --global user.email "zel@kakao.com" && git config --global user.name "Sharknia"

      - name: Gatsby Build and Deploy to GitHub Pages
        run: |
          npm run gatsby build
          npx gh-pages -d public